[template]
src = "php/php.ini.tpl"
dest = "/etc/php/7.1/apache2/php.ini"
uid = 0
gid = 0
mode = "0644"
keys = [
  "/php/max/execution/time",
  "/php/max/file/uploads"
  "/php/max/input/time",
  "/php/max/input/vars",
  "/php/memory/limit",
  "/php/post/max/size",
  "/php/upload/max/filesize"
]
